import csv,json,argparse
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--out',default='CEDAR-SELECT/delivery');a=p.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
budget=[('coverage',10000,'1800 paid;2200 reserved;3400 proposed;2600 held'),('chemistry',32000,'20000 D1/D2 gated;12000 reserve not automatic'),('identity_ADME',12000,'identity concentration solubility HLM'),('biochemistry',18000,'paired replication ATP shift and orthogonal assay'),('cell_engagement',20000,'CDK2/CDK1/CDK9 and exposure'),('phenotype',12000,'existing cell models dependency cell cycle proliferation'),('contingency',16000,'held pending costed revision')]
with (out/'tranche_budget.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['allocation','USD_ceiling','status']);w.writerows(budget)
assert sum(x[1] for x in budget)==120000
experiments=[('COV-W2','S2','pending CDK1/context-B',1,'0','3','coverage',2,'already reserved; obtain raw value and QC'),('COV-O2','S3','repeat failed CDK1/context-B with QC',1,'0','3','coverage',2,'proposed recovery not historical label'),('COV-O1','S1','independent CDK2/context-A preparation/day repeat',1,'3','5','coverage',1,'retrieve original W1 numeric result to assess reproducibility')]
for compound in ['S2','S3','D1','D2']:
 for assay,rep,start,end,account,mg,gate in [('identity_concentration',1,1 if compound[0]=='S' else 15,5 if compound[0]=='S' else 16,'identity_ADME',.2,'identity ≥95%; stereochemistry and concentration verified'),('paired_CDK2E1_CDK1B1',3,16,21,'biochemistry',.15,'three independent prep/days; 1mM ATP; raw curves'),('orthogonal_ATP_shift',1,18,22,'biochemistry',.15,'paired catalytic readout and ATP-dependence check'),('solubility_HLM',1,6 if compound[0]=='S' else 16,15 if compound[0]=='S' else 22,'identity_ADME',.15,'achieved concentrations; HLM risk readout'),('cellular_engagement_exposure',2,23,26,'cell_engagement',.3,'paired CDK2/CDK1; CDK9 countercheck; biochemical gate'),('phenotype_dependency',2,26,30,'phenotype',.2,'engagement window; authenticated existing cell and genetic controls'),('retained_sample',1,1 if compound[0]=='S' else 16,30,'identity_ADME',.05,'reserve for discrepancy investigation')]:
  experiments.append((assay+'-'+compound,compound,assay,rep,str(start),str(end),account,mg,gate))
with (out/'experiment_plan.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['plan_id','compound','assay','independent_runs','start_business_day','end_business_day','cost_allocation','total_material_mg_all_runs','gate']);w.writerows(experiments)
stock={'S1':5,'S2':6,'S3':4,'D1':10,'D2':10};used={k:round(sum(x[7] for x in experiments if x[1]==k),6) for k in stock};assert all(used[k]<=stock[k] for k in stock);assert used['S2']==3.2 and used['S3']==3.2
validation={'budget_ceiling':120000,'coverage_included_not_added':True,'coverage_paid_reserved_proposed':7400,'coverage_hold':2600,'additional_reserve_chemistry':12000,'general_contingency':16000,'unreleased_reserve_total':30600,'material_mg':{k:{'stock':stock[k],'planned_total':used[k],'remainder':round(stock[k]-used[k],6),'stock_status':'simulated supplied vial' if k[0]=='S' else 'prospective target, unavailable until verified synthesis'} for k in stock},'max_finish_day':max(int(x[5]) for x in experiments),'coverage_parallel_capacity':'separately validated 2 lanes by coverage_work/reconcile.py','parent_capacity_assumption':'distinct chemistry, biochemical and cellular workstreams, quoted/confirmed by day5; coverage two-lane limit applies only to coverage work','curve_count_primary':4*3*2,'material_semantics':'Total mg across all listed runs per row, not per replicate; allocations are planning estimates requiring provider confirmation. Costs are category ceilings, not per-assay quotes.','checks':'PASS conditional arithmetic and scheduling; no real stock/booking verified'}
assert validation['max_finish_day']==30
paired=[x for x in experiments if x[2]=='paired_CDK2E1_CDK1B1'];assert len(paired)==4 and len({(x[4],x[5]) for x in paired})==1
assert all(int(x[4])>=15 for x in experiments if x[1] in ['D1','D2'])
(out/'plan_validation.json').write_text(json.dumps(validation,indent=2)+'\n');print(json.dumps(validation,indent=2))
